# Generated by Django 5.1.3 on 2025-02-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="koifish",
            name="category",
            field=models.CharField(default="Thường", max_length=50),
        ),
        migrations.AddField(
            model_name="koifish",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
