# Generated by Django 5.1.3 on 2025-02-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_koifish_category_koifish_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="koifish",
            name="image",
            field=models.CharField(
                default="https://askoi.vn/wp-content/uploads/2019/09/koi-nhat-shiro-utsuri.jpg",
                max_length=100,
            ),
        ),
    ]
